---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/Kahrilas-latex-CV.tex
geometry: margin=1in

title: "CV"
author: "Ian J. Kahrilas"

jobtitle: "Clinical Psychology PhD Candidate"
address: "203 Columbia Avenue, Park Ridge, IL 60068"
fontawesome: yes
email: ikahrilas@luc.edu
github: ikahrilas
osf: "z5vea"

keywords: R Markdown, academic CV, template

#fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---
  
# Education

*Loyola University Chicago* \hfill 2016-Present  
Master of Arts with Distinction \hfill Cumulative GPA: 3.99  
Clinical Psychology  
Master's Thesis: The Neurobiological Correlates of Savoring  
  
*University of Illinois at Urbana-Champaign*  \hfill 2011-2014  
B.S., Psychology  \hfill Cumulative GPA: 3.96  

# Awards & Honors
**-**Loyola University Chicago Thesis of the Year Award in the Social Sciences ($300).  
**-**2018 Kobler Travel Award ($400).  
**-**2017 Heckler Fellowship Award ($3,000).  
**-**Graduate Merit Tuition Scholarship, Loyola University Chicago: August 2016-Present.  
**-**Emanuel Donchin Award for outstanding undergraduate research assistant in cognitive neuroscience ($300).  
**-**UIUC Dean’s List: Fall 2011, Spring 2012, Fall 2012, Spring 2013, Fall 2013, Spring 2014.  

# Publications
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
Alexander, R., Aragon, O., Bookwala, J., Cherbuin, N., Gatt, J.M., **Kahrilas, I.J.**,  Kastener, N., Lawrence, A., Lowe, L., Morrison, R.G., Mueller, S.C., Papadelis, C., Polnaszek, K.L., Richter, S.H., Silton, R.L., & Styliadis, C. (revise & resubmit). Happiness and wellbeing: A review of human and animal research.  
*authorship is alphabetical  

**Kahrilas, I.J.** & Kahrilas, P.J. (2019). Reflux disease and idiopathic lung fibrosis: Association does not imply causation. Chest, 155(1), 5-6. https://doi.org/10.1016/j.chest.2018.08.1062  

**Kahrilas, I.J.**, Smith, J.L., Bryant, F.B., Silton, R.L. (revise & resubmit). Savoring the moment: A link between affectivity and depression. International Journal of Well Being.
Silton, R.L., Kahrilas, I.J., Skymba, H.V., Bryant, F.B., & Heller, W. (in press). Positive emotion regulation and wellbeing: Implications for risk and resilience across the lifespan. Emotion.  

Silton, R.L., Polnaszek, K.L., **Kahrilas, I.J.**, Dickson, D.A., Miller, G.A., & Heller, W. (revise & resubmit). Low positive affect is associated with reduced prefrontal cortical activity in remitted depression.  

\endgroup

## Other Publications

Student. 1905. "The Pearson Co-efficient of Correlation." Supplement to Report of 1904, Arthur Guinness Son & Company.

Student. 1904. "The Application of the 'Law of Error' to the Work of the Brewery." Report, Arthur Guinness Son & Company.

# References

Available upon request, though likely would include Karl Pearson and Ronald A. Fisher. Please send corrections, feedback, or details of missed publications (of which there are probably a few) to svmille@clemson.edu.
