---
title: "CV"
author: "Ian J. Kahrilas"
email: ian.kahrilas@gmail.com
phone: "(847) 209-1217"
output:
  pdf_document:
    latex_engine: pdflatex
    template: Kahrilas-latex-CV.tex
  html_document:
    df_print: paged
fontfamilyoptions: sc, osf
fontsize: 12pt
geometry: margin=1in
github: ikahrilas
jobtitle: Clinical Psychology Ph.D. Candidate
keywords: R Markdown, academic CV, template
linkcolor: blue
osf: z5vea
fontawesome: yes
address: 1032 W. Sheridan Rd. · Loyola University Chicago · Chicago, IL 60660
urlcolor: blue
---

# EDUCATION
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
**Loyola University Chicago** \hfill 2016 - Present\
Doctor of Philosophy (anticipated graduation date: May 2022)\
Clinical Psychology\
\hspace{.5in} *Doctoral Dissertation: Individual Differences and Neural Correlates of Positive*\
\hspace{.5in} *Emotion Reactivity and Regulation in Depression*\
\hspace{.5in} Proposal Date: September 10th, 2020\
\hspace{.5in} Anticipated Defense: May 2021

**Loyola University Chicago** \hfill 2016 - 2018\
Master of Arts with Distinction\
Clinical Psychology\
\hspace{.5in} *Master's Thesis: The Neurobiological Correlates of Savoring*
  
**University of Illinois at Urbana-Champaign**  \hfill 2011 - 2014  
Bachelor of Science\
Psychology

# AWARDS & HONORS
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
\textbullet \hspace{.5mm} Graduate Merit-Based Tuition Scholarship,\hfill 2016 - Present\
\hspace{3.7mm} Loyola University Chicago\
\textbullet \hspace{.5mm} Graduate Merit-Based Research Assistantship, \hfill 2016 - Present\
\hspace{3.7mm} Loyola University Chicago\
\textbullet \hspace{.5mm} Graduate Travel Award, Loyola University Chicago \hfill 2016 - Present\
\textbullet \hspace{.5mm} Kobler Travel Award ($400) \hfill 2018, 2019\
\textbullet \hspace{.5mm} Loyola University Chicago Thesis of the Year Award in the \hfill 2018\
\hspace{3.7mm} Social Sciences ($300)\
\textbullet \hspace{.5mm} Loyola University Chicago 3 Minute Thesis Competition - 1\textsuperscript{st} place Psychology \hfill 2017\
\textbullet \hspace{.5mm} Heckler Fellowship Award ($3,000) \hfill 2017\
\textbullet \hspace{.5mm} Emanuel Donchin Award for outstanding undergraduate research \hfill 2014\
\hspace{3.7mm} assistant in cognitive neuroscience\
\textbullet \hspace{.5mm} Dean’s List, University of Illinois at Urbana-Champaign \hfill Fall 2011 - Spring 2014  

# CLINICAL EXPERIENCE
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
**Advanced Neuropsychology Extern** \hfill July 2020 - Present\
*Psychology Service*\
Edward Hines, Jr. VA Hospital, Hines, IL\
Supervisor: David Kinsinger, Ph.D,., ABPP-CN
\vspace{-2.5mm}

* Conduct outpatient neuropsychological testing using a flexible battery approach with a veteran population in face-to-face and telehealth modalities.
* Presenting concerns include traumatic brain injury, substance use disorder, posttraumatic stress disorder, dementia, stroke, and medically-related cognitive impairment.
* Conduct semi-structured clinical interviews with clients and family members, complete integrated reports based on neuropsychological assessment, medical record review, and clinical interview.
* Receive weekly individual supervision and bi-weekly group supervision.
* Attend weekly didactic seminars and grand rounds in neuroradiology and neuropsychology.

**Advanced Psychotherapy Extern** \hfill July 2019 - July 2020\
*Mood and Anxiety Disorders Program*\
University of Illinois at Chicago, Department of Psychiatry, Chicago, IL\
Supervisor: Jennifer Duffecy, Ph.D.
\vspace{-2.5mm}

* Provided long-term, weekly individual psychotherapy for adults from diverse cultural and socioeconomic backgrounds using a primarily cognitive-behavioral approach in face-to-face and telehealth modalities.
* Presenting concerns included anxiety, panic, depression, bipolar, and phobias. Patients also presented with comorbid health conditions, such as Ebstein's Anomaly, idiopathic hypersomnia, ulcerative colitis, and cognitive concerns.
* Received weekly individual supervision.
* Consulted with health professionals and applied relevant behavioral and cognitive strategies.

**Adult Neuropsychology Extern** \hfill July 2018 - July 2019\
*Adult Neuropsychology Service*\
NorthShore University HealthSystem & Evanston Hospital, Evanston, IL\
Supervisors: Leslie Guidotti-Breting, Ph.D., ABPP-CN, Elizabeth Geary, Ph.D., ABPP-CN, & Jerry Sweet, Ph.D., ABPP-CN
\vspace{-2.5mm}

* Conducted neuropsychological assessments utilizing a flexible battery approach with a culturally diverse adult outpatient and inpatient population (ages 18 to 90+).
* Presenting concerns included dementia, stroke, traumatic brain injury, concussion, epilepsy, learning disorders, attention-deficit hyperactivity disorder, psychiatric disorders, autism spectrum disorders, and neurological disorders (e.g., normal pressure hydrocephalus, pachymeningitis).
* Conducted pre- and post-surgical candidacy evaluations for adults pursuing bariatric, left ventricular assist device (LVAD), and shunt surgeries.
* Received weekly individual and group supervision in planning test selection, implementing, interpreting, writing, and communicating results of neuropsychological evaluations.
* Wrote neuropsychological reports synthesizing information gathered in testing and clinical interview.
* Attended didactic conferences and seminars devoted to topics in neurology, neuropsychology, and neuroanatomy.
* Completed pre-season baseline concussion testing for a Chicago-based professional sport franchise.

**Psychotherapy Extern** \hfill September 2017 - May 2018\
*The Wellness Center in Student Counseling Services*\
Loyola University Chicago, Chicago, IL\   
Supervisors: Scott Leon, Ph.D., Jerome Wagner, Ph.D., Daniel Keller, Ph.D., Dianna Stencel, MSW, LCSW
\vspace{-2.5mm}

* Provided brief individual psychotherapy (eight sessions) to undergraduate students using CBT, ACT, and IPT approaches. Presenting problems included mood disorders, trauma, relationship concerns, and grief.
* Conducted intake interviews, designed and implemented intervention plans, provided crisis management, and consulted with other therapists, psychiatrists, and nutritionists.
* Co-facilitated two eight-week mindfulness-based cognitive therapy groups for students with mood disorders.
* Received weekly individual and group supervision and participated in weekly didactic training.

# RELATED CLINICAL EXPERIENCE
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
**Adult Neuropsychology Technician** \hfill July 2019 - July 2020\
*Adult Neuropsychology Service*\
NorthShore University HealthSystem & Evanston Hospital, Evanston, IL\  
Supervisors: Leslie Guidotti-Breting, Ph.D., ABPP-CN, Elizabeth Geary, Ph.D., ABPP-CN, & Jerry Sweet, Ph.D., ABPP-CN
\vspace{-2.5mm}

* Conducted neuropsychological assessments utilizing a flexible battery approach with a culturally diverse adult outpatient and inpatient population (ages 18 to 90+).
* Presenting concerns included dementia, stroke, traumatic brain injury, concussion, epilepsy, learning disorders, attention-deficit hyperactivity disorder, psychiatric disorders, autism spectrum disorders, and neurological disorders (e.g., normal pressure hydrocephalus, pachymeningitis).
* Conduct pre- and post-surgical candidacy evaluations for adults pursuing bariatric, left ventricular assist device (LVAD), and shunt surgeries.
* Wrote neuropsychological reports synthesizing information gathered in testing and clinical interview.

**Pediatric Neuropsychology Technician** \hfill January 2015 - June 2016\
Dirksen Center for Neurobehavioral Health, Arlington Heights, IL\
Supervisors: Courtney Dirksen, Ph.D. & Maribel Serrato, Psy.D. 
\vspace{-2.5mm}

* Observed, administered, and scored neuropsychological batteries.
* Worked with a culturally diverse population ranging from childhood to early adulthood.
* Prepared data tables to be used in neuropsychological reports.
* Wrote behavioral observations to be used in neuropsychological reports.

**Stress Management Peer** \hfill August 2012 - December 2012\
*Stress Management Peers*\
University of Illinois at Urbana-Champaign, Urbana-Champaign, IL
\vspace{-2.5mm}

* Conducted stress-management workshops for various groups on campus.
* Collaborated with university health center to disseminate information and resources regarding mental health.

# PUBLICATIONS AND PRESENTATIONS
\vspace{-\baselineskip}
\hrulefill
\vspace{-.2\baselineskip}

\underline{\textbf{Publications}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
**Kahrilas, I.J.**, Smith, J.L., Silton, R.L., & Bryant, F.B. (2020). Savoring the moment: A link between affectivity and depression. *International Journal of Well Being*, *10*(2), 19-36. http://dx.doi.org/10.5502/ijw.v10i2.779

Silton, R.L., **Kahrilas, I.J.**, Skymba, H.V., Bryant, F.B., & Heller, W. (2020). Regulating positive emotions: Implications for promoting well-being in individuals with depression. *Emotion*, *20*(1), 93-97. http://dx.doi.org/10.1037/emo0000675

**Kahrilas, I.J.** & Kahrilas, P.J. (2019). Reflux disease and idiopathic lung fibrosis: Association does not imply causation. *Chest*, *155*(1), 5-6. https://doi.org/10.1016/j.chest.2018.08.1062 

\underline{\textbf{Manuscripts Under Review}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
Alexander, R., Aragon, O., Bookwala, J., Cherbuin, N., Gatt, J.M., **Kahrilas, I.J.**,  Kastener, N., Lawrence, A., Lowe, L., Morrison, R.G., Mueller, S.C., Papadelis, C., Polnaszek, K.L., Richter, S.H., Silton, R.L., & Styliadis, C. (revise & resubmit). The neuroscience of positive emotions and affect: Implications for promoting happiness and wellbeing.  
*authorship is alphabetical  

Rainey, V.R., Stockdale, L., Flores-Lamb, V., Mullins, T.K., Gjorgieva, E., **Kahrilas, I.J.**, Morrison, R.G., & Silton, R.L. (under review). Monolingual and bilingual cognitive control differences on a color-word Stroop task. 
\endgroup

\underline{\textbf{Invited Manuscripts}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
**Kahrilas, I.J.**, Rauch, A., Miller, G.A., & Silton, R.L. (invited manuscript). Replicability and transparency in ERP research: Guidelines and recommendations. *International Journal of Psychophysiology*.
\endgroup

\underline{\textbf{Manuscripts in Preparation}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
Dickson, D.A., Lee, C., **Kahrilas, I.J.**, & Silton, R.L. (in preparation). Positive affectivity distinctly influences negative interpretation bias in individuals with remitted depression.

**Kahrilas, I.J.**, Bryant, F.B., Miller, G.A., & Silton, R.L. (in preparation). The neural correlates of positive emotion reactivity and regulation.

**Kahrilas, I.J.**, Conley, C.S., Silton, R.L. (in preparation). The neural correlates of emotion reactivity in depression.

**Kahrilas, I.J.**, Conley, C.S., Silton, R.L. (in preparation). Positively mindful: Changes in positive emotion reactivity after eight weeks of Headspace.

\endgroup

\underline{\textbf{Conference Talks}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
Silton, R.L., **Kahrilas, I.J.**, Polnaszek, K.L., Smith, J.L., & Bryant, F.B. (2018). Psychological and neural correlates of positive emotion regulation. Symposium paper accepted for presentation at Society for Research in Psychopathology (SRP), Indianapolis, IN.

\endgroup

\underline{\textbf{Poster Presentations \& Abstracts}}

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
**Kahrilas I.J.**, Bryant, F.B., Polnaszek, K.L., Diviero, A., Schroer, M., Hussaini, A., Silton, R.L. (2019, September). Positive emotion regulation: The neural correlates of savoring. Poster session presented at Society for Psychophysiological Research Annual Meeting, Washington, DC.  

**Kahrilas, I.J.**, Sims, E., Dosamantes, N., Ward, S., Silton, R.L., & Morrison, R.G. (2019, March). Functional differences in a cognitive control network in older adults with exceptional memory. Poster session presented at the Cognitive Neuroscience Society Annual Meeting, San Francisco, CA.  

Huguenel, B., Silton, R., Duffecy, J. Economides, M., **Kahrilas, I.J.**, & Conley, C. (2019, March). Technology- based mindfulness and depression in college students. Poster session presented at the University of Michigan Depression on College Campuses Conference, Ann Arbor, MI.  
   
Polnaszek, K.L., **Kahrilas I.J.**, Murray, C., Bohnert A., Hellman K.M., Tu, F.F., Silton, R.L. (2018, September). Pain Symptomatology Influences Inhibitory Control Through Psychological Symptoms in Emerging Adults. Poster session presented at Society for Research in Psychopathology (SRP), Indianapolis, IN.  

**Kahrilas, I.J.**, Dickson, D.A., Lee, C., Silton, R.L. (2018, April). Positive affectivity distinctly influences negative interpretation bias in individuals with remitted depression. Poster session presented at Society for Affective Science (SAS), Los Angeles, CA.

Polnaszek, K.L., **Kahrilas, I.J.**, Bates, C., Bohnert, A., Hellman, K.M., Tu, F.F., & Silton, R.L. (2018, February). Inhibitory control and psychological symptoms influence pain symptomatology in emerging adults. Poster session presented at International Neuropsychological Society (INS), Washington, D.C.

Domokos, F.E., Polnaszek, K.L., **Kahrilas, I.J.**, Bryant, F.B., Tu, F.F., Hellman, K.M., & Silton, R.L. (2017, April). Savoring past and present positive events boosts positive affect for individuals with pain symptoms. Poster session presented at the Midwestern Psychological Association Annual Meeting, Chicago, IL

**Kahrilas, I.J.**, Bryant, F.B., Kais, L.A., Domokos, F.E., & Silton, R.L. (2017, April). Savoring the moment distinctly mediates the relationship between affect and depression. Poster session presented at Society for Affective Science (SAS), Boston, MA.

Meinke, M., **Kahrilas, I.J.**, Polnaszek, K., Silton, R.L. (2017, April). Executive function as a moderator of the relationship between psychache and suicidal ideation. Poster session presented at Loyola Undergraduate Research Opportunities Program (LUROP) Research Symposium, Chicago, IL.

Keefer, L., Craft, J., Dowjotas, K., **Kahrilas, I. J.**, Roman, S., Pandolfino, J. E. (2015). Symptom reporting among PPI non responders may be driven by esophageal hypervigilance and not reflux phenotype. Gastroenterology, 148(4):S-147.

Quinton, S., **Kahrilas, I. J.**, Kassam, A., Srivastava, A.K., Komanduri, S., & Keefer, L. (2014). When the diagnosis is pancreatic cancer: an analysis of coping strategies among endosonographers. Gastrointestinal Endoscopy, 79(5), AB309.

Quinton, S., Srivastava, A.K., **Kahrilas, I. J.**, Keefer, L., Komanduri, S. (2014). "Breaking the bad news:" A survey of practice patterns in disclosing a pancreatic cancer diagnosis among US endosonographers. Gastrointestinal Endoscopy, 79(5), AB193.

Ballou, S., Quinton, S., **Kahrilas, I.**, Lackner, J., Keefer, L. (2014). Impairment of daily activities in young adult women with Irritable Bowel syndrome. Annals of Behavioral Medicine, 47, S33.

# INVITED TALKS & LECTURES
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}

**Kahrilas, I.J.** (2021, May). *The neural correlates of positive emotion reactivity and regulation in depression*. Invited seminar talk at Loyola University Chicago's Department of Neuroscience, Chicago, IL.

**Kahrilas, I.J.** (2017, 2018, 2019, & 2020). *Career paths in clinical psychology*. Invited professional panel speaker in Loyola University Chicago's undergraduate psychology internship course, Chicago, IL.

**Kahrilas, I.J.** (2019, May). *Case presentation on frontotemporal dementia (FTD): Patient with behavioral variant FTD*. Presentation at NorthShore University HealthSystem, Evanston, IL.

**Kahrilas, I.J.** (2018, November). *Case presentation on Attention Deficit Hyperactivity Disorder (ADHD)*. Presentation at NorthShore University HealthSystem, Evanston, Illinois.

**Kahrilas, I.J.** (2018, November). *Case presentation on epilepsy*. Presentation at NorthShore University HealthSystem.

**Kahrilas, I.J.** (2018, April). *Case presentation and formulation for adjustment disorder*. Presentation at Loyola University Chicago, Chicago, IL.

**Kahrilas, I.J.** (2018, March). *Case presentation and formulation for sexuality, sexual identity, and coming out*. Presentation at Loyola University Chicago, Chicago, IL. 

\endgroup
\endgroup
# RESEARCH EXPERIENCE
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
**Graduate Research Assistant** \hfill August 2016 - Present\
*Wellbeing and Emotion Lab*  
Loyola University Chicago, Chicago, IL   
Principal Investigator: Rebecca Levin Silton, Ph.D.  
\vspace{-.25mm}

* Investigate the neural correlates of positive emotion regulation in psychological disorders with behavioral and electroencephalography (EEG) methods.
* Design novel EEG emotion regulation paradigm using open-source stimuli.
* Design, oversee, and collect data for study investigating how neural correlates of positive and negative emotion regulation vary as a function of individual differences.
* Contribute to design, launch, and coordination of randomized controlled trial investigating the effectiveness of an eight-week mindfulness intervention on reducing depressive symptomatology and modifying individual differences and neural correlates pertaining to emotion reactivity and regulation in college students with elevated depression.
* Organize task assignments and mentored team of research assistants.
* Present and co-author conference presentation and talks at international conferences (e.g., Society for Affective Science annual meeting, Society for Psychophysiological Research, Society for Research in Psychopathology annual meeting).
* Author and co-author peer-reviewed manuscripts and grant applications.
* Write Institutional Review Board applications.
* Supervise and mentor undergraduate independent research projects.
* Develop expertise in psychological experimental paradigm software (E-Prime) and open-source programming languages (R, Python).

**Graduate Research Assistant** \hfill August 2018 - May 2019\   
*Cognitive and Affective Neuroscience Lab*\
Loyola University Chicago, Chicago, IL\
Principal Investigator: Robert Morrison, Ph.D.  
\vspace{-.25mm}

* Investigated neural correlates of cognitive ability in "super-ager" population using EEG methods, such as source analysis.
* Ran and oversaw research projects.
* Programmed and developed EEG experimental paradigms.
* Ran statistical analyses.
* Administered experimental protocol to participants and cleaned data for EEG processing.
* Presented findings at the Cognitive Neuroscience Society annual meeting.

**Research Assistant** \hfill May 2012 -  August 2014\
*Center for Psychosocial Research in GI*    
Northwestern University Feinberg School of Medicine\
Principal Investigator: Laurie Keefer, Ph.D.
\vspace{-2.5mm}

* Assisted with data entry & organization for the Irritable Bowel Syndrome Outcome Study (IBSOS).
* Composed blog articles for CPRGI website about the stress response’s effect on gastrointestinal function and the importance of colon cancer screening.
* Converted questionnaire measures into online survey format for project exploring the relation between cognitive flexibility and functional gastrointestinal disorders.
* Contacted and scheduled participants for research participation.
* Screened potential research participants and obtained consent for research participation.

**Undergraduate Research Assistant** \hfill August 2013 - May 2014\
*Social, Cognitive, Personality, and Emotional Neuroscience Lab*\
University of Illinois at Urbana-Champaign, Champaign, IL\
Principal Investigator: Florin Dolcos, Ph.D.  
\vspace{-.25mm}

* Scheduled and conducted behavioral and fMRI sessions investigating the neural correlates of emotion's impact on attention.
* Modeled 3-D representations of brain structures using neuroimaging software.
* Prepared stimuli for experimental sessions.
* Managed databases for various experiments being conducted by the lab.

# TEACHING AND MENTORSHIP EXPERIENCE
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}

**Instructor** \hfill Fall 2019 & Fall 2020\
*Statistics*\
Loyola University Chicago, Chicago, IL\
Teaching Mentors: Fred B. Bryant, Ph.D. & Rebecca L. Silton, Ph.D.\
\vspace{-.5mm}

* Designed syllabus and curriculum for face-to-face and online formats. 
* Delivered weekly lectures. 
* Evaluated student coursework and performance. 
* Mentored and assisted students.  

**Graduate Student Research Mentor** \hfill 2018 - Present\
*Loyola Undergraduate Research Opportunities Program (LUROP)*\
Loyola University Chicago, Chicago IL
\vspace{-2.5mm}

* Supervised four undergraduate students' Senior Thesis projects (Provost Fellowship & Mulcahy Scholars Program), hypothesis generation, literature review, study design, data analysis, manuscript and report writing, and presentations.

**Peer Supervisor** \hfill July 2019 - July 2020\
NorthShore University HealthSystem\
Supervisors: Leslie Guidotti-Breting, Ph.D., ABPP-CN, Elizabeth Geary, Ph.D., ABPP-CN, & Jerry Sweet, Ph.D., ABPP-CN\
\vspace{-.25mm}

* Read through and provided feedback on neuropsychological reports prepared by peers.
* Demonstrated standardized administration of neuropsychological assessments.
* Observed peers' administration of neuropsychological assessment and provided feedback.

**Guest Lecturer** \hfill Fall 2018\
Adult Intellectual and Personality Assessment (Graduate)\
*Lecture: Neuropsychological Assessment*\
Instructor: Noni Gaylord-Harden, Ph.D.\
Loyola University Chicago, Chicago, IL

**Graduate Student Supervisor** \hfill September 2017 - November 2019\
*Department of Clinical Psychology*\
Loyola University Chicago, Chicago, IL\
Supervisors: Scott Leon, Ph.D. & Maryse Richards, Ph.D.
\vspace{-2.5mm}

* Supervised first- and second-year clinical psychology graduate students in developing clinical interviewing and case conceptualization skills. Reviewed mock intake and therapy sessions, evaluated clinical reports, and provided written and verbal feedback.
* Delivered feedback to a second-year student on the development of supervisory skills. Received feedback on supervision skills from faculty supervisor.

**Instructor** \hfill June 2018 & July 2019\
*Loyola University Chicago Pre-College Summer Scholars Program*\
Loyola University Chicago, Chicago, IL\
Course: Introduction to Data Science with R
\vspace{-2.5mm}

* Delivered intensive week-long introductory course on programming, data visualization, data management/manipulation, and statistical procedures through lectures and hands-on exercises in the R programming language.

**Graduate Teaching Assistant** \hfill August 2019 - December 2019\
*Department of Psychology*\
Loyola University Chicago\
Course: Statistics\
Instructor: Lawrence Behmer, Ph.D.  
\vspace{-.25mm}

* Graded exams and bi-weekly homework assignments.

Course: Learning & Behavior \hfill January 2019 - May 2019\
Instructor: Eric Gobel, Ph.D.  
\vspace{-.25mm}

* Administered and graded assignments and exams.
* Calculated grades.
* Held weekly office hours.

Course: Neuroscience \hfill August 2018 - December 2018\
Instructor: Robert Morrison, Ph.D.
\vspace{-2.5mm}

* Administered and graded assignments and exams.
* Calculated grades.
* Graded weekly discussion questions and blog posts.
* Disseminated information regarding weekly neuroscience seminars.

Course: Psychology of Creativity \hfill August 2018 - December 2018\
Instructor: Robert Morrison, Ph.D.
\vspace{-2.5mm}

* Administered and graded assignments and exams.
* Calculated grades.
* Graded weekly discussion questions and blog posts.

Course: Introduction to Psychology \hfill September 2016 - May 2017\
Instructor: Richard Bowen, Ph.D.  
\vspace{-.25mm}

* Administered and graded assignments and exams.
* Calculated grades.

Course: Learning and Behavior \hfill September 2016 - May 2017\
Instructor: Jerome Wagner, Ph.D.  
\vspace{-.25mm}

* Administered and graded assignments and exams.
* Calculated grades.

Course: Psychology of Personality \hfill September 2016 - May 2017\
Instructor: Jerome Wagner, Ph.D.  
\vspace{-.25mm}

* Administered and graded assignments and exams.
* Calculated grades.

# LEADERSHIP AND PROFESSIONAL SERVICE
\vspace{-\baselineskip}
\hrulefill
\vspace{-.2\baselineskip}

\underline{\textbf{Committee Membership}}

**Clinical Graduate Student Technology Committee** \hfill September 2019 - Present\
Clinical Psychology Program, Loyola University Chicago   

**Clinical Graduate Student Information Committee** \hfill September 2018 - Present\
Clinical Psychology Program, Loyola University Chicago

**Graduate Student Advisory Council** \hfill \hfill September 2017 - Present\
Loyola University Chicago

**Clinical Colloquium Committee**, *Chair* \hfill September 2017 - May 2018\
Clinical Psychology Program, Loyola University Chicago   

\underline{\textbf{Ad Hoc Manuscript Reviews}} \hfill \underline{Number of Reviews}\

Reviewer, *Journal of Personality* \hspace{3.31in} 1\
Co-Reviewer, *Journal of Adolescence* \hspace{3.03in} 1\
Co-Reviewer, *Psychopathology & Behavioral Assessment* \hspace{1.65in} 2\
Co-Reviewer, *Journal of Experimental Child Psychology* \hspace{1.68in} 1\

# PROFESSIONAL AFFILIATIONS
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}
Society for Psychophysiological Research (SPR)\
American Psychological Association (APA) Graduate Student Affiliate\
APA Division 12, Clinical Psychology\
APA Division 40, Society for Clinical Neuropsychology\
Cognitive Neuroscience Society (CNS)\
Society for Affective Science (SAS)\
International Neuropsychological Society (INS)\
Society for Research in Psychopathology (SRP)\

# STATISTICAL APPLICATIONS
\vspace{-\baselineskip}
\hrulefill
\vspace{-.7\baselineskip}

* \textbf{R} - Open-source programming language designed for statistical computing and graphics.\
* \textbf{lme4} - R package for fitting linear mixed-effects models.\
* \textbf{lavaan} - R package for structural equation modeling.\
* \textbf{ggplot2} - R package for data visualization.\
* \textbf{tidyverse} - Suite of R packages for common data science tasks (e.g., data manipulation, data cleaning, functional programming)\
* \textbf{rmarkdown} - R package for creating reproducible documents that integrate code and text.\
* \textbf{SPSS}\
* \textbf{HLM} - Software for hierarchical linear modeling.\


